sqs_prefix = "reporting-interaction-shutdown"
region = "{{region}}"
sns_topic = "arn:aws:sns:us-east-1:{{accountArn}}:{{env}}-{{service}}-instance-shutdowns"
commands = [["/serviceShutdown.py", "stop"]]